# Generated by Django 2.2.19 on 2021-09-14 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210914_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество ингредиента: 1 единица')], verbose_name='Количество ингредиента'),
        ),
    ]
